name: Generate animated snake
on:
  schedule: [{ cron: "0 0 * * 1" }]  # every Monday
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: sabinAnwar
          outputs: |
            dist/snake.svg
      - uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/snake.svg
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
